# Generated by Django 6.0 on 2025-12-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='map_name',
            field=models.CharField(default='Erangel', max_length=100),
        ),
    ]
