# Generated by Django 6.0 on 2025-12-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='tournament_covers/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tournament_logos/'),
        ),
    ]
