# Generated by Django 5.2 on 2025-12-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_team_logo_alter_match_id_alter_score_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='featured_images/')),
                ('link_url', models.CharField(default='/', max_length=255)),
                ('content_type', models.CharField(choices=[('MAIN', 'Main Hero (Large)'), ('SIDE', 'Side Card (Small Vertical)'), ('BOTTOM', 'Bottom Card (Small Horizontal)')], default='MAIN', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Higher number appears first/top')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
