# Generated by Django 5.2 on 2025-12-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_featuredcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pro',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a Pro Organiser (only configurable by Superuser).'),
        ),
    ]
