# Generated by Django 5.2 on 2025-12-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='layout_config',
            field=models.JSONField(blank=True, default=dict, help_text='Config for image generation: start_x, start_y, row_height, font_size, etc.'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='theme_image',
            field=models.ImageField(blank=True, null=True, upload_to='tournament_themes/'),
        ),
    ]
