# Generated by Django 5.2 on 2025-12-21 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_tournament_layout_config_tournament_theme_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Theme', max_length=100)),
                ('theme_image', models.ImageField(upload_to='tournament_themes/')),
                ('custom_font', models.FileField(blank=True, help_text='Upload .ttf or .otf font file', null=True, upload_to='tournament_fonts/')),
                ('layout_config', models.JSONField(blank=True, default=dict)),
                ('teams_per_page', models.IntegerField(default=20, help_text='Number of teams to show per image page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='tournaments.tournament')),
            ],
        ),
    ]
